//
//  The Bad Batch Tech's Datapad firmware for Arduino Mega 2560.
//  Created by Diego J. Arévalo.
//  https://github.com/therebelagent/Tech-Datapad
//  2021 v 1.0.
//

//Naviagation Menu
#define DISPLAY_INACTIVY_INTERVAL 5 //Seconds
#define NAVIGATION_MENU_BUTTONS_ITEMS 7
#define NAVIGATION_MENU_BUTTON_COLOR DISPLAY_RING_COLOR
#define NAVIGATION_MENU_BUTTON_BACK_COLOR 0x0004
#define NAVIGATION_MENU_BUTTON_PRESS_COLOR TFT_DARKCYAN
#define NAVIGATION_MENU_BANNER_TEXT "main menu"
#define NAVIGATION_MENU_BUTTON_0_TEXT "dlh"
#define NAVIGATION_MENU_BUTTON_1_TEXT "cst"
#define NAVIGATION_MENU_BUTTON_2_TEXT "fcc"
#define NAVIGATION_MENU_BUTTON_3_TEXT "rsc"
#define NAVIGATION_MENU_BUTTON_4_TEXT "cpu"
#define NAVIGATION_MENU_BUTTON_5_TEXT "et"
#define NAVIGATION_MENU_BUTTON_6_TEXT "ec"

//Basic Grid DDS
#define DISPLAY_BACK_COLOR 0x0002
#define DISPLAY_RING_COLOR TFT_CYAN
#define GRID_OUTER_FRAME_OFFSET 4
#define DISPLAY_GRID_LINE_COLOR 0x3D38
#define DEFAULT_GRID_LINES 20

//Explosive Charges DDS
#define LIGHT_BLUE_CIRCLE_COLOR DISPLAY_RING_COLOR
#define BLUE_INNER_CIRCLE_COLOR 0x3D38
#define DARK_GREEN_BULLSEYE_CIRCLE_COLOR 0x003333
#define BULLSEYE_OFFSET 2
#define BULLSEYE_BORDER_CIRCLE_RELATIVE_DIAMETER 0.97
#define BULLSEYE_FIRST_CIRCLE_RELATIVE_DIAMETER 0.83
#define BULLSEYE_SECOND_CIRCLE_RELATIVE_DIAMETER 0.51
#define BULLSEYE_THIRD_CIRCLE_RELATIVE_DIAMETER 0.17

//Enemy Targets DDS
#define ENEMY_TARGET_GRID_LINES 14
#define ENEMY_TARGET_COLOR 0xF945
#define LIGHT_ENEMY_TARGET_COLOR 0xEF5D
#define ENEMY_TARGET_HEADER_A_TEXT "scanner"
#define ENEMY_TARGET_HEADER_B_TEXT "active"
#define A_INNER_CIRCLE_RELATIVE_DIAMETER 0.56
#define A_INNER_CIRCLE_RELATIVE_BOTTOM_DISTANCE 0.19
#define B_INNER_CIRCLE_RELATIVE_DIAMETER 0.23
#define B_INNER_CIRCLE_RELATIVE_BOTTOM_DISTANCE 0.26

//Cannon Powering Up DDS
#define CANNON_POWERING_UP_FIXED_EMERCENCY "Emergency"
#define CANNON_POWERING_UP_FIXED_POWER "Power"
#define CANNON_POWERED_DOWN_COLOR ENEMY_TARGET_COLOR
#define CANNON_POWERED_UP_COLOR 0x0740
#define DEPLETED_CANNON_BANNER "depleted"
#define POWERED_CANNON_DOWN_BANNER "charging"
#define POWERED_UP_CANNON_BANNER "charged"
#define CANNON_RELATIVE_WIDTH 0.72
#define CANNON_RELATIVE_HEIGHT 0.21

//Rear Axle Stabilizer Calibration DDS
#define REAR_AXLE_STABILIZER_CALIBRATION_REPAIRING "repairing"
#define REAR_AXLE_STABILIZER_CALIBRATION_COMPLETE "complete"
#define REAR_AXLE_STABILIZER_CALIBRATION_PROGRESS_BAR_SEGMENTS 9
#define REAR_AXLE_STABILIZER_CALIBRATION_PROGRESS_BAR_SMALL_SEGMENT_COLOR 0xF9C0
#define REAR_AXLE_STABILIZER_CALIBRATION_PROGRESS_BAR_REGULAR_SEGMENT_COLOR 0xFBA0

//Forging Chain Codes DDS
#define FORGING_CHAIN_CODES_RECTANGULAR_FRAME_COLOR 0xE6C8

//Forging Chain Codes Paragraph 1.
const char FCC_PARAGRAPH1_SENTENCE1[] PROGMEM = "This is where I wanna be";
const char FCC_PARAGRAPH1_SENTENCE2[] PROGMEM = "You got me for a bargain";
const char FCC_PARAGRAPH1_SENTENCE3[] PROGMEM = "This is where I wanna be";
const char FCC_PARAGRAPH1_SENTENCE4[] PROGMEM = "1";
const char FCC_PARAGRAPH1_SENTENCE5[] PROGMEM = "2";
const char FCC_PARAGRAPH1_SENTENCE6[] PROGMEM = "it s the best option you ve got";
const char FCC_PARAGRAPH1_SENTENCE7[] PROGMEM = "You make money, I make money";
const char FCC_PARAGRAPH1_SENTENCE8[] PROGMEM = "Hey kid You ready for this";
const char FCC_PARAGRAPH1_SENTENCE9[] PROGMEM = "That's the only way I know";
const char FCC_PARAGRAPH1_SENTENCE10[] PROGMEM = "Allow me to decide for you";
const char FCC_PARAGRAPH1_SENTENCE11[] PROGMEM = "You're a generation one";
const char FCC_PARAGRAPH1_SENTENCE12[] PROGMEM = "";
const char FCC_PARAGRAPH1_SENTENCE13[] PROGMEM = "Ok";
const char FCC_PARAGRAPH1_SENTENCE14[] PROGMEM = "and I watch your back";
const char FCC_PARAGRAPH1_SENTENCE15[] PROGMEM = "With the heat on you";
const char FCC_PARAGRAPH1_SENTENCE16[] PROGMEM = "";
const char FCC_PARAGRAPH1_SENTENCE17[] PROGMEM = "We move fast";
const char FCC_PARAGRAPH1_SENTENCE18[] PROGMEM = "  Stay out of trouble";
const char FCC_PARAGRAPH1_SENTENCE19[] PROGMEM = "  I'm angry at myself";
const char FCC_PARAGRAPH1_SENTENCE20[] PROGMEM = "Ok";
const char FCC_PARAGRAPH1_SENTENCE21[] PROGMEM = "Ok";
const char FCC_PARAGRAPH1_SENTENCE22[] PROGMEM = "You're not a droid";
const char FCC_PARAGRAPH1_SENTENCE23[] PROGMEM = "Omega, this is Rex";

const char *const forgingChainCodesParagraph1[] PROGMEM = {FCC_PARAGRAPH1_SENTENCE1, FCC_PARAGRAPH1_SENTENCE2, FCC_PARAGRAPH1_SENTENCE3, FCC_PARAGRAPH1_SENTENCE4, FCC_PARAGRAPH1_SENTENCE5, FCC_PARAGRAPH1_SENTENCE6, FCC_PARAGRAPH1_SENTENCE7, FCC_PARAGRAPH1_SENTENCE8, FCC_PARAGRAPH1_SENTENCE9, FCC_PARAGRAPH1_SENTENCE10, FCC_PARAGRAPH1_SENTENCE11, FCC_PARAGRAPH1_SENTENCE12, FCC_PARAGRAPH1_SENTENCE13, FCC_PARAGRAPH1_SENTENCE14, FCC_PARAGRAPH1_SENTENCE15, FCC_PARAGRAPH1_SENTENCE16, FCC_PARAGRAPH1_SENTENCE17, FCC_PARAGRAPH1_SENTENCE18, FCC_PARAGRAPH1_SENTENCE19, FCC_PARAGRAPH1_SENTENCE20, FCC_PARAGRAPH1_SENTENCE21, FCC_PARAGRAPH1_SENTENCE22, FCC_PARAGRAPH1_SENTENCE23};

//Forging Chain Codes Paragraph 2.
const char FCC_PARAGRAPH2_SENTENCE1[] PROGMEM = "Well, Take care trooper";
const char FCC_PARAGRAPH2_SENTENCE2[] PROGMEM = "You got me for a bargain";
const char FCC_PARAGRAPH2_SENTENCE3[] PROGMEM = "This is where I wanna be";
const char FCC_PARAGRAPH2_SENTENCE4[] PROGMEM = "";
const char FCC_PARAGRAPH2_SENTENCE5[] PROGMEM = "1";
const char FCC_PARAGRAPH2_SENTENCE6[] PROGMEM = "Ok";
const char FCC_PARAGRAPH2_SENTENCE7[] PROGMEM = "  Only if I can go with them";
const char FCC_PARAGRAPH2_SENTENCE8[] PROGMEM = "  Here";
const char FCC_PARAGRAPH2_SENTENCE9[] PROGMEM = "  I'm angry at myself";
const char FCC_PARAGRAPH2_SENTENCE10[] PROGMEM = "Ok";
const char FCC_PARAGRAPH2_SENTENCE11[] PROGMEM = "Ok";
const char FCC_PARAGRAPH2_SENTENCE12[] PROGMEM = "";
const char FCC_PARAGRAPH2_SENTENCE13[] PROGMEM = "";
const char FCC_PARAGRAPH2_SENTENCE14[] PROGMEM = "";
const char FCC_PARAGRAPH2_SENTENCE15[] PROGMEM = "";
const char FCC_PARAGRAPH2_SENTENCE16[] PROGMEM = "";
const char FCC_PARAGRAPH2_SENTENCE17[] PROGMEM = "";
const char FCC_PARAGRAPH2_SENTENCE18[] PROGMEM = "";
const char FCC_PARAGRAPH2_SENTENCE19[] PROGMEM = "You shouldn't be angry at him";
const char FCC_PARAGRAPH2_SENTENCE20[] PROGMEM = "  Huh. Maybe you are different";
const char FCC_PARAGRAPH2_SENTENCE21[] PROGMEM = "  Why are you giving it to us";
const char FCC_PARAGRAPH2_SENTENCE22[] PROGMEM = "  you know how to reach us";
const char FCC_PARAGRAPH2_SENTENCE23[] PROGMEM = "  I just told you you're in";
const char FCC_PARAGRAPH2_SENTENCE24[] PROGMEM = "  If you're ever in a bind";
const char FCC_PARAGRAPH2_SENTENCE25[] PROGMEM = "  2";

const char *const forgingChainCodesParagraph2[] PROGMEM = {FCC_PARAGRAPH2_SENTENCE1, FCC_PARAGRAPH2_SENTENCE2, FCC_PARAGRAPH2_SENTENCE3, FCC_PARAGRAPH2_SENTENCE4, FCC_PARAGRAPH2_SENTENCE5, FCC_PARAGRAPH2_SENTENCE6, FCC_PARAGRAPH2_SENTENCE7, FCC_PARAGRAPH2_SENTENCE8, FCC_PARAGRAPH2_SENTENCE9, FCC_PARAGRAPH2_SENTENCE10, FCC_PARAGRAPH2_SENTENCE11, FCC_PARAGRAPH2_SENTENCE12, FCC_PARAGRAPH2_SENTENCE13, FCC_PARAGRAPH2_SENTENCE14, FCC_PARAGRAPH2_SENTENCE15, FCC_PARAGRAPH2_SENTENCE16, FCC_PARAGRAPH2_SENTENCE17, FCC_PARAGRAPH2_SENTENCE18, FCC_PARAGRAPH2_SENTENCE19, FCC_PARAGRAPH2_SENTENCE20, FCC_PARAGRAPH2_SENTENCE21, FCC_PARAGRAPH2_SENTENCE22, FCC_PARAGRAPH2_SENTENCE23, FCC_PARAGRAPH2_SENTENCE24, FCC_PARAGRAPH2_SENTENCE25};

//Forging Chain Codes Paragraph 3.
const char FCC_PARAGRAPH3_SENTENCE1[] PROGMEM = "If this is where you want to be";
const char FCC_PARAGRAPH3_SENTENCE2[] PROGMEM = "then this is where you'll stay";
const char FCC_PARAGRAPH3_SENTENCE3[] PROGMEM = "In the end we all choose sides";
const char FCC_PARAGRAPH3_SENTENCE4[] PROGMEM = "Yeah I guess I've been around";
const char FCC_PARAGRAPH3_SENTENCE5[] PROGMEM = "I stunned him when he jumped";
const char FCC_PARAGRAPH3_SENTENCE6[] PROGMEM = "From the lines on your face";
const char FCC_PARAGRAPH3_SENTENCE7[] PROGMEM = "1";
const char FCC_PARAGRAPH3_SENTENCE8[] PROGMEM = "2";
const char FCC_PARAGRAPH3_SENTENCE9[] PROGMEM = "3";
const char FCC_PARAGRAPH3_SENTENCE10[] PROGMEM = "We don't leave our own behind";
const char FCC_PARAGRAPH3_SENTENCE11[] PROGMEM = "Let's blow something up Yeah";
const char FCC_PARAGRAPH3_SENTENCE12[] PROGMEM = "You shouldn't be angry at him";
const char FCC_PARAGRAPH3_SENTENCE13[] PROGMEM = "We don't leave our own behind";
const char FCC_PARAGRAPH3_SENTENCE14[] PROGMEM = "Take it from me";
const char FCC_PARAGRAPH3_SENTENCE15[] PROGMEM = "";
const char FCC_PARAGRAPH3_SENTENCE16[] PROGMEM = "4";
const char FCC_PARAGRAPH3_SENTENCE17[] PROGMEM = "Ok";

const char *const forgingChainCodesParagraph3[] PROGMEM = {FCC_PARAGRAPH3_SENTENCE1, FCC_PARAGRAPH3_SENTENCE2, FCC_PARAGRAPH3_SENTENCE3, FCC_PARAGRAPH3_SENTENCE4, FCC_PARAGRAPH3_SENTENCE5, FCC_PARAGRAPH3_SENTENCE6, FCC_PARAGRAPH3_SENTENCE7, FCC_PARAGRAPH3_SENTENCE8, FCC_PARAGRAPH3_SENTENCE9, FCC_PARAGRAPH3_SENTENCE10, FCC_PARAGRAPH3_SENTENCE11, FCC_PARAGRAPH3_SENTENCE12, FCC_PARAGRAPH3_SENTENCE13, FCC_PARAGRAPH3_SENTENCE14, FCC_PARAGRAPH3_SENTENCE15, FCC_PARAGRAPH3_SENTENCE16, FCC_PARAGRAPH3_SENTENCE17};

//Forging Chain Codes Paragraph 4.
const char FCC_PARAGRAPH4_SENTENCE1[] PROGMEM = "Tech, you think you could forge";
const char FCC_PARAGRAPH4_SENTENCE2[] PROGMEM = "some chain codes?";
const char FCC_PARAGRAPH4_SENTENCE3[] PROGMEM = "I only learned of them moments";
const char FCC_PARAGRAPH4_SENTENCE4[] PROGMEM = "ago but yes";
const char FCC_PARAGRAPH4_SENTENCE5[] PROGMEM = "";
const char FCC_PARAGRAPH4_SENTENCE6[] PROGMEM = "";
const char FCC_PARAGRAPH4_SENTENCE7[] PROGMEM = "I left Kamino with you";
const char FCC_PARAGRAPH4_SENTENCE8[] PROGMEM = "I know you re in";
const char FCC_PARAGRAPH4_SENTENCE9[] PROGMEM = "I guess we're in";
const char FCC_PARAGRAPH4_SENTENCE10[] PROGMEM = "This one we like";
const char FCC_PARAGRAPH4_SENTENCE11[] PROGMEM = "Where's the Jedi?";
const char FCC_PARAGRAPH4_SENTENCE12[] PROGMEM = "He can't help it";
const char FCC_PARAGRAPH4_SENTENCE13[] PROGMEM = "He didn't make it";
const char FCC_PARAGRAPH4_SENTENCE14[] PROGMEM = "";
const char FCC_PARAGRAPH4_SENTENCE15[] PROGMEM = "";
const char FCC_PARAGRAPH4_SENTENCE16[] PROGMEM = "";
const char FCC_PARAGRAPH4_SENTENCE17[] PROGMEM = "In progress";
const char FCC_PARAGRAPH4_SENTENCE18[] PROGMEM = "The encryption shouldn't be";
const char FCC_PARAGRAPH4_SENTENCE19[] PROGMEM = "a problem";
const char FCC_PARAGRAPH4_SENTENCE20[] PROGMEM = "Ok";

const char *const forgingChainCodesParagraph4[] PROGMEM = {FCC_PARAGRAPH4_SENTENCE1, FCC_PARAGRAPH4_SENTENCE2, FCC_PARAGRAPH4_SENTENCE3, FCC_PARAGRAPH4_SENTENCE4, FCC_PARAGRAPH4_SENTENCE5, FCC_PARAGRAPH4_SENTENCE6, FCC_PARAGRAPH4_SENTENCE7, FCC_PARAGRAPH4_SENTENCE8, FCC_PARAGRAPH4_SENTENCE9, FCC_PARAGRAPH4_SENTENCE10, FCC_PARAGRAPH4_SENTENCE11, FCC_PARAGRAPH4_SENTENCE12, FCC_PARAGRAPH4_SENTENCE13, FCC_PARAGRAPH4_SENTENCE14, FCC_PARAGRAPH4_SENTENCE15, FCC_PARAGRAPH4_SENTENCE16, FCC_PARAGRAPH4_SENTENCE17, FCC_PARAGRAPH4_SENTENCE18, FCC_PARAGRAPH4_SENTENCE19, FCC_PARAGRAPH4_SENTENCE20};

//Forging Chain Codes Paragraph 5.
const char FCC_PARAGRAPH5_SENTENCE1[] PROGMEM = "Everybody's talking about it";
const char FCC_PARAGRAPH5_SENTENCE2[] PROGMEM = "What kind of evaluation?";
const char FCC_PARAGRAPH5_SENTENCE3[] PROGMEM = "Hopefully not mental";
const char FCC_PARAGRAPH5_SENTENCE4[] PROGMEM = "Clearly we'd never pass that";
const char FCC_PARAGRAPH5_SENTENCE5[] PROGMEM = "";
const char FCC_PARAGRAPH5_SENTENCE6[] PROGMEM = "";
const char FCC_PARAGRAPH5_SENTENCE7[] PROGMEM = "Things are back to normal";
const char FCC_PARAGRAPH5_SENTENCE8[] PROGMEM = "That's not going near my rack";
const char FCC_PARAGRAPH5_SENTENCE9[] PROGMEM = "That's not her ugly side?";
const char FCC_PARAGRAPH5_SENTENCE10[] PROGMEM = "What was that, goggles?";
const char FCC_PARAGRAPH5_SENTENCE11[] PROGMEM = "";
const char FCC_PARAGRAPH5_SENTENCE12[] PROGMEM = "";
const char FCC_PARAGRAPH5_SENTENCE13[] PROGMEM = "";
const char FCC_PARAGRAPH5_SENTENCE14[] PROGMEM = "Tech? What was the war like?";
const char FCC_PARAGRAPH5_SENTENCE15[] PROGMEM = "Whoa! So many proton torpedoes";
const char FCC_PARAGRAPH5_SENTENCE16[] PROGMEM = "Come here, beautiful";
const char FCC_PARAGRAPH5_SENTENCE17[] PROGMEM = "But, what was it like?";
const char FCC_PARAGRAPH5_SENTENCE18[] PROGMEM = "Hmm? I just told you";
const char FCC_PARAGRAPH5_SENTENCE19[] PROGMEM = "";
const char FCC_PARAGRAPH5_SENTENCE20[] PROGMEM = "";
const char FCC_PARAGRAPH5_SENTENCE21[] PROGMEM = "It'd be weirder if you had";
const char FCC_PARAGRAPH5_SENTENCE22[] PROGMEM = "Sorry, kid. This one’s all mine";

const char *const forgingChainCodesParagraph5[] PROGMEM = {FCC_PARAGRAPH5_SENTENCE1, FCC_PARAGRAPH5_SENTENCE2, FCC_PARAGRAPH5_SENTENCE3, FCC_PARAGRAPH5_SENTENCE4, FCC_PARAGRAPH5_SENTENCE5, FCC_PARAGRAPH5_SENTENCE6, FCC_PARAGRAPH5_SENTENCE7, FCC_PARAGRAPH5_SENTENCE8, FCC_PARAGRAPH5_SENTENCE9, FCC_PARAGRAPH5_SENTENCE10, FCC_PARAGRAPH5_SENTENCE11, FCC_PARAGRAPH5_SENTENCE12, FCC_PARAGRAPH5_SENTENCE13, FCC_PARAGRAPH5_SENTENCE14, FCC_PARAGRAPH5_SENTENCE15, FCC_PARAGRAPH5_SENTENCE16, FCC_PARAGRAPH5_SENTENCE17, FCC_PARAGRAPH5_SENTENCE18, FCC_PARAGRAPH5_SENTENCE19, FCC_PARAGRAPH5_SENTENCE20, FCC_PARAGRAPH5_SENTENCE21, FCC_PARAGRAPH5_SENTENCE22};

//Door Lock Hacking DDS

#define DISPLAY_FIXED_DETAILS_COLOR 0x01FF

//Door Lock Hacking Paragraph 1.
const char DLH_PARAGRAPH1_SENTENCE1[] PROGMEM = "11001";
const char DLH_PARAGRAPH1_SENTENCE2[] PROGMEM = "0101";
const char DLH_PARAGRAPH1_SENTENCE3[] PROGMEM = "001";
const char DLH_PARAGRAPH1_SENTENCE4[] PROGMEM = "11101";
const char DLH_PARAGRAPH1_SENTENCE5[] PROGMEM = "001";
const char DLH_PARAGRAPH1_SENTENCE6[] PROGMEM = "11001";
const char DLH_PARAGRAPH1_SENTENCE7[] PROGMEM = "01010";
const char DLH_PARAGRAPH1_SENTENCE8[] PROGMEM = "01";
const char DLH_PARAGRAPH1_SENTENCE9[] PROGMEM = "01010";
const char DLH_PARAGRAPH1_SENTENCE10[] PROGMEM = "01";
const char DLH_PARAGRAPH1_SENTENCE11[] PROGMEM = "";
const char DLH_PARAGRAPH1_SENTENCE12[] PROGMEM = "00011";
const char DLH_PARAGRAPH1_SENTENCE13[] PROGMEM = "1";
const char DLH_PARAGRAPH1_SENTENCE14[] PROGMEM = "11001";
const char DLH_PARAGRAPH1_SENTENCE15[] PROGMEM = "0101";
const char DLH_PARAGRAPH1_SENTENCE16[] PROGMEM = "11101";
const char DLH_PARAGRAPH1_SENTENCE17[] PROGMEM = "001";
const char DLH_PARAGRAPH1_SENTENCE18[] PROGMEM = "11001";
const char DLH_PARAGRAPH1_SENTENCE19[] PROGMEM = "01010";
const char DLH_PARAGRAPH1_SENTENCE20[] PROGMEM = "01";
const char DLH_PARAGRAPH1_SENTENCE21[] PROGMEM = "01010";
const char DLH_PARAGRAPH1_SENTENCE22[] PROGMEM = "01";
const char DLH_PARAGRAPH1_SENTENCE23[] PROGMEM = "";
const char DLH_PARAGRAPH1_SENTENCE24[] PROGMEM = "11001";
const char DLH_PARAGRAPH1_SENTENCE25[] PROGMEM = "0101";
const char DLH_PARAGRAPH1_SENTENCE26[] PROGMEM = "001";
const char DLH_PARAGRAPH1_SENTENCE27[] PROGMEM = "11101";
const char DLH_PARAGRAPH1_SENTENCE28[] PROGMEM = "001";
const char DLH_PARAGRAPH1_SENTENCE29[] PROGMEM = "11001";
const char DLH_PARAGRAPH1_SENTENCE30[] PROGMEM = "01010";
const char DLH_PARAGRAPH1_SENTENCE31[] PROGMEM = "01";
const char DLH_PARAGRAPH1_SENTENCE32[] PROGMEM = "01010";
const char DLH_PARAGRAPH1_SENTENCE33[] PROGMEM = "01";
const char DLH_PARAGRAPH1_SENTENCE34[] PROGMEM = "";
const char DLH_PARAGRAPH1_SENTENCE35[] PROGMEM = "00011";
const char DLH_PARAGRAPH1_SENTENCE36[] PROGMEM = "1";

const char *const doorLockHackingParagraph1[] PROGMEM = {DLH_PARAGRAPH1_SENTENCE1, DLH_PARAGRAPH1_SENTENCE2, DLH_PARAGRAPH1_SENTENCE3, DLH_PARAGRAPH1_SENTENCE4, DLH_PARAGRAPH1_SENTENCE5, DLH_PARAGRAPH1_SENTENCE6, DLH_PARAGRAPH1_SENTENCE7, DLH_PARAGRAPH1_SENTENCE8, DLH_PARAGRAPH1_SENTENCE9, DLH_PARAGRAPH1_SENTENCE10, DLH_PARAGRAPH1_SENTENCE11, DLH_PARAGRAPH1_SENTENCE12, DLH_PARAGRAPH1_SENTENCE13, DLH_PARAGRAPH1_SENTENCE14, DLH_PARAGRAPH1_SENTENCE15, DLH_PARAGRAPH1_SENTENCE16, DLH_PARAGRAPH1_SENTENCE17, DLH_PARAGRAPH1_SENTENCE18, DLH_PARAGRAPH1_SENTENCE19, DLH_PARAGRAPH1_SENTENCE20, DLH_PARAGRAPH1_SENTENCE21, DLH_PARAGRAPH1_SENTENCE22, DLH_PARAGRAPH1_SENTENCE23, DLH_PARAGRAPH1_SENTENCE24, DLH_PARAGRAPH1_SENTENCE26, DLH_PARAGRAPH1_SENTENCE27, DLH_PARAGRAPH1_SENTENCE28, DLH_PARAGRAPH1_SENTENCE29, DLH_PARAGRAPH1_SENTENCE30, DLH_PARAGRAPH1_SENTENCE31, DLH_PARAGRAPH1_SENTENCE32, DLH_PARAGRAPH1_SENTENCE33, DLH_PARAGRAPH1_SENTENCE34, DLH_PARAGRAPH1_SENTENCE35, DLH_PARAGRAPH1_SENTENCE36};