//
//  The Bad Batch Tech's Datapad firmware for Arduino Mega 2560.
//  Created by Diego J. Arévalo.
//  https://github.com/therebelagent/Tech-Datapad
//  2021 v 1.0.
//

//Basic Grid DDS
#define DISPLAY_BACK_COLOR 0x0002
#define DISPLAY_RING_COLOR TFT_CYAN
#define GRID_OUTER_FRAME_OFFSET 3
#define DISPLAY_GRID_LINE_COLOR 0x3D38
#define GRID_LINES 19

//Explosive Charges DDS
#define LIGHT_BLUE_CIRCLE_COLOR DISPLAY_RING_COLOR
#define BLUE_INNER_CIRCLE_COLOR 0x3D38
#define DARK_GREEN_BULLSEYE_CIRCLE_COLOR 0x003333
#define BULLSEYE_OFFSET 2
#define BULLSEYE_BORDER_CIRCLE_RELATIVE_DIAMETER 0.97
#define BULLSEYE_FIRST_CIRCLE_RELATIVE_DIAMETER 0.83
#define BULLSEYE_SECOND_CIRCLE_RELATIVE_DIAMETER 0.51
#define BULLSEYE_THIRD_CIRCLE_RELATIVE_DIAMETER 0.17

//Enemy Targets DDS
#define ENEMY_TARGET_COLOR 0xF945
#define LIGHT_ENEMY_TARGET_COLOR 0xEF5D
#define ENEMY_TARGET_HEADER_A_TEXT "Star Wars"
#define ENEMY_TARGET_HEADER_B_TEXT "The Bad Batch"
#define A_INNER_CIRCLE_RELATIVE_DIAMETER 0.56
#define A_INNER_CIRCLE_RELATIVE_BOTTOM_DISTANCE 0.19
#define B_INNER_CIRCLE_RELATIVE_DIAMETER 0.23
#define B_INNER_CIRCLE_RELATIVE_BOTTOM_DISTANCE 0.26

//Cannon Powering Up DDS
#define CANNON_POWERING_UP_FIXED_EMERCENCY "Emergency"
#define CANNON_POWERING_UP_FIXED_POWER "Power"
#define CANNON_POWERED_DOWN_COLOR 0xF945
#define CANNON_POWERED_UP_COLOR 0x0740
#define DEPLETED_CANNON_BANNER "depleted"
#define POWERED_CANNON_DOWN_BANNER "charging"
#define POWERED_UP_CANNON_BANNER "charged"
#define CANNON_RELATIVE_WIDTH 0.72
#define CANNON_RELATIVE_HEIGHT 0.21

//Rear Axle Stabilizer Calibration DDS
#define REAR_AXLE_STABILIZER_CALIBRATION_REPAIRING "repairing"
#define REAR_AXLE_STABILIZER_CALIBRATION_COMPLETE "complete"
#define REAR_AXLE_STABILIZER_CALIBRATION_PROGRESS_BAR_SEGMENTS 9
#define REAR_AXLE_STABILIZER_CALIBRATION_PROGRESS_BAR_SMALL_SEGMENT_COLOR 0xF9C0
#define REAR_AXLE_STABILIZER_CALIBRATION_PROGRESS_BAR_REGULAR_SEGMENT_COLOR 0xFBA0